# Configuration for Raspberry Pi
data_root: /mnt/hdd/wikipedia-links
data_remote: https://dumps.wikimedia.org/enwiki/
data_date: '20190301'

# Available memory (log base 2)
free_memory: 28  # 2**28 is 256MB
temp_dir: '/home/pi/wikipedia-links'

# Tables to download and unzip from remote
tables:
  # https://www.mediawiki.org/wiki/Manual:Pagelinks_table
  pagelinks:
    names:
      - pl_from
      - pl_namespace
      - pl_title
      - pl_from_namespace

  # https://www.mediawiki.org/wiki/Manual:Page_table
  page:
    names:
      - page_id
      - page_namespace
      - page_title
      - page_restrictions
      - page_is_redirect
      - page_is_new
      - page_random
      - page_touched
      - page_links_updated
      - page_latest
      - page_len
      - page_content_model
      - page_lang

  # https://www.mediawiki.org/wiki/Manual:Redirect_table
  redirect:
    names:
      - rd_from
      - rd_namespace
      - rd_title
      - rd_interwiki
      - rd_fragment

# Files generated during processing
gen:
  page_direct_unsorted: 'gen/page_direct_unsorted.csv'
  page_redirect_unsorted: 'gen/page_redirect_unsorted.csv'
  page_direct: 'gen/page_direct.csv'
  page_redirect: 'gen/page_redirect.csv'
  page_redirect_resolved: 'gen/page_redirect_resolved.csv'
  page: 'page.csv'
  pagelinks_unresolved: 'gen/pagelinks_unresolved.csv'

