load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "extraction",
    srcs = [
        "bsearch.py",
        "constants.py",
        "download.py",
        "extsort.py",
        "idbytitle.py",
        "pagelinks.py",
        "pipeline.py"
    ],
    main = "pipeline.py"
)